#include "../src/vrg.h"

#define val(...) vrg(val_,__VA_ARGS__)
val()
val(a)
val((t)a)
val(a,b)
val((t)a,b)
val(a,b,c)
val((t)a, 3+4,c)
val(a,b,c,d)
val((t)a,b,c,d)
val(a,b,c,d,e)
val((t)a,b,c,d,e)
val(a,b,c,d,e,f(3+x))
val((t)a,b,c,(p?1:2),e,f)
val(a,b,c,d,e,f,g)
val((t)a,b,c,d,e,f,g)
val(a,b,c,d,e,(3,4),g,h)
val((t)a,b,c,d,e,f,g,h)
val(a,b,c,d,e,f,g,h,i)
val((t)a,b,c,d,e,f,g,h,i)

#undef val
#define val(...) vrg_(val_,__VA_ARGS__)
val()
val(a)
val((t)a)
val(a,b)
val((t)a,b)
val(a,b,c)
val((t)a, 3+4,c)
val(a,b,c,d)
val((t)a,b,c,d)
val(a,b,c,d,e)
val((t)a,b,c,d,e)
val(a,b,c,d,e,f(3+x))
val((t)a,b,c,(p?1:2),e,f)
val(a,b,c,d,e,f,g)
val((t)a,b,c,d,e,f,g)
val(a,b,c,d,e,(3,4),g,h)
val((t)a,b,c,d,e,f,g,h)
val(a,b,c,d,e,f,g,h,i)
val((t)a,b,c,d,e,f,g,h,i)

